import { Box } from "@chakra-ui/react";
import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Unscode | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Unscode
    </Box>
  );
};

export default Home;
